package com.tunacake.webTutorial.entities;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.UUID;


@Getter/* This will tell Spring that this is a Lombok getter. */
@Setter/* This will tell Spring that this is a Lombok setter. */
@AllArgsConstructor/* This will tell Spring that this is a Lombok all-args constructor. */
@NoArgsConstructor/* This will tell Spring that this is a Lombok no-args constructor. */
@Entity /* This will tell Spring that this is a JPA entity. Shortcut for "@Entity + @Id + @GeneratedValue". This annotation is used to map an entity to a database table */
@Table(name = "employees") /* The @Table annotation tells Spring that this entity will be mapped to the "employees" named table in the database */
public class EmployeeEntity {

    @Id /* The @Id annotation tells Spring that this field is the primary key of the table */
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.UUID) /* The @GeneratedValue annotation tells Spring that this field will be auto-generated by the database and strategy states how the auto-generated value will be generated*/
    private UUID id;
    private String name;
    private String email;
    private Integer age;
    private LocalDate dateofjoining;
    private boolean isActive;

}
