spring.application.name=webTutorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./db/webTutorial
spring.datasource.username=juneth
spring.datasource.password=521463
spring.jpa.hibernate.ddl-auto=create
